### ISSUE TITLE
Unreviewed commit on main!

### ISSUE THREAD

**Issue by cb-heimdall** [coinbase/cb-cookie-manager#15]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/cb-cookie-manager/compare/51e7bb657f43a6bd24976dd32a88bf65fe235033...53103518281c85bae86e0a219719390c62b66d10) was merged to main by joshuaostrom-cb.

Comment with appropriate number of :+1: to approve.

---

Reviewed requirements satisfied? No
Ancestors reviewed? Yes

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/cb-cookie-manager&ref=52cc419991093fdd959ceef87f2c45f3c014167a)

**Comment by snehkoul-cb** [comment]
👍
